# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eadsax}
  s.version = "0.0.1"
  s.authors = ["Jason Ronallo"]
  s.email = %q{jronallo@gmail.com}
  s.homepage = %q{http://github.com/jronallo/eadsax}
  s.summary = %q{Parse EAD XML}
  s.description = %q{Parse EAD XML using sax-machine.}
  s.rubyforge_project = 'eadsax'

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]
  s.licenses = ["MIT"]

  s.add_runtime_dependency(%q<sax-machine>)
  s.add_runtime_dependency(%q<trollop>)
  s.add_development_dependency(%q<rspec>)  
end

